### ISSUE TITLE
All Actions forwared to last created action server

### ISSUE THREAD

**Issue by weber-niklas** [turag-ev/EB23#12]
When running 
```bash
ros2 run imam console_controle
```
and then calling any action only the last action added to the action list in the servers.py file will be executed.

**Comment by weber-niklas** [comment]
Update:
It seems as if the action servers receive the goal, however all execute callbacks are being called with the properties of the last added Action Callback

**Comment by Zarnack** [comment]
Fixed issue with a920283dc58aba5ece69673908c52fe0ba15d48a
