### ISSUE TITLE
Discuss amount of threads needed to be used for IMAM

### ISSUE THREAD

**Issue by Zarnack** [turag-ev/EB23#13]
Currently concurrent goals are handled via a [MultiThreadedExecutor()](https://docs.ros.org/en/foxy/Concepts/About-Executors.html#types-of-executors).  
By default it uses at most as many threads as the current CPU has --> an 8 thread CPU equals to a maximum of 8 concurrent possible goals
However this can be changed via the "num_threads" argument detailed [here](https://docs.ros2.org/foxy/api/rclpy/api/execution_and_callbacks.html#rclpy.executors.MultiThreadedExecutor). 
As the final system will be run on a Raspberry Pi with a mere 4 cores, we should set a higher limit here to support more concurrent goals.  
I would propose  a limit to 8 threads to not overload the system.

**Comment by weber-niklas** [comment]
I agree that having the option to run more than 4 actions at once is a necessity and should be implemented on the Pi. 
Do we know how much stress those threads actually put on the system or is 8 just a safe guesstimate? Having 8 actions running simultaneously should be enough tho imo.

**Comment by weber-niklas** [comment]
Result: 8
