### ISSUE TITLE
Remove Large Jupiter Notebook Files

### ISSUE THREAD

**Issue by weber-niklas** [turag-ev/EB23#80]
Currently 80% of this repository is jupiter notebooks. That has to change back to its actual composition.
Please remove unnecessary files.

**Comment by VladimirFokow** [comment]
This commit (to the `pathfinding` branch) should solve this:
https://github.com/turag-ev/EB23/commit/7a330329537fa7840223b90541cf42a6deaf4e41

Note: 
the language distribution (in the Languages tab on the right) should update when these changes occur on the `main` branch ([How Linguist works on GitHub.com](https://github.com/github-linguist/linguist/blob/master/docs/how-linguist-works.md#how-linguist-works-on-githubcom))

**Comment by VladimirFokow** [comment]
I've converted the 2 jupyter notebooks into .py files – to reduce space, but at the same time to save that code (the .py files don't take up a lot of space). 

Anyway, these 2 files were used just for testing, so they can be totally deleted in the future.

**Comment by weber-niklas** [comment]
Thank you! I will merge this after validating the compatibility of the current state on the pathfinding branch with dev. @AT-Haas did some testing on  a new feature which was not working yet. Will have to filter that out for now and maybe add later after more testing/ improving.

**Comment by weber-niklas** [comment]
Made a separate branch to remove untested feature and merged into dev.

Thanks for the help! :)
